/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.student;
import util.DatabaseConnector;
/**
 *
 * @author Kruti
 */
public class studentForm extends javax.swing.JPanel {

    /**
     * Creates new form studentForm
     */
    public studentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldOfStudyButtonGroup = new javax.swing.ButtonGroup();
        titleLabel = new javax.swing.JLabel();
        yourNameLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        lastNameTextField = new javax.swing.JTextField();
        studentIdLabel = new javax.swing.JLabel();
        studentIDTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        appointmentReasonLabel = new javax.swing.JLabel();
        fieldofStudyLabel = new javax.swing.JLabel();
        misRadioButton = new javax.swing.JRadioButton();
        mpmRadioButton = new javax.swing.JRadioButton();
        mbtRadio = new javax.swing.JRadioButton();
        analyticsRadio = new javax.swing.JRadioButton();
        mraRadioButton = new javax.swing.JRadioButton();
        cyberRadio = new javax.swing.JRadioButton();
        pickDateLabel = new javax.swing.JLabel();
        describeLabek = new javax.swing.JLabel();
        describeTextField = new javax.swing.JTextField();
        uploadIdLabel = new javax.swing.JLabel();
        uploadImageButton = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        appointForChooser = new javax.swing.JComboBox<>();
        datePicker = new com.toedter.calendar.JDateChooser();

        titleLabel.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Student Appointment Form");

        yourNameLabel.setBackground(new java.awt.Color(255, 51, 51));
        yourNameLabel.setText("Your Name *");

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });

        studentIdLabel.setText("Student ID# *");

        emailLabel.setText("Your Email *");

        phoneLabel.setText("Phone # *");

        phoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneTextFieldActionPerformed(evt);
            }
        });

        appointmentReasonLabel.setText("What are you making appointment for?");

        fieldofStudyLabel.setText("Field of Study *");

        fieldOfStudyButtonGroup.add(misRadioButton);
        misRadioButton.setText("Msc. Information Systems");
        misRadioButton.setActionCommand("Information Systems");
        misRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                misRadioButtonActionPerformed(evt);
            }
        });

        fieldOfStudyButtonGroup.add(mpmRadioButton);
        mpmRadioButton.setText("MSc. Project Management");
        mpmRadioButton.setActionCommand("PROJECT MANAGEMENT");

        fieldOfStudyButtonGroup.add(mbtRadio);
        mbtRadio.setText("MSc. Biotechnology");
        mbtRadio.setActionCommand("BIOTECHNOLOGY");

        fieldOfStudyButtonGroup.add(analyticsRadio);
        analyticsRadio.setText("MSc. Analytics");
        analyticsRadio.setActionCommand("ANALYTICS");
        analyticsRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyticsRadioActionPerformed(evt);
            }
        });

        fieldOfStudyButtonGroup.add(mraRadioButton);
        mraRadioButton.setText("MSc. Regulatory Affairs");
        mraRadioButton.setActionCommand("REGULATORY AFFAIRS");

        fieldOfStudyButtonGroup.add(cyberRadio);
        cyberRadio.setText("MSc. Cyber-Physical Systems");
        cyberRadio.setActionCommand("CYBER-PHYSICAL SYSTEMS");

        pickDateLabel.setText("Pick a Date");

        describeLabek.setText("Describe about the reason for appointment");

        describeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                describeTextFieldActionPerformed(evt);
            }
        });

        uploadIdLabel.setText("Upload Student ID * ");

        uploadImageButton.setText("Browse");
        uploadImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImageButtonActionPerformed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        appointForChooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Advising", "Exam related queries", "Course related concerns", "others" }));
        appointForChooser.setSelectedIndex(-1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(misRadioButton)
                            .addComponent(mbtRadio)
                            .addComponent(fieldofStudyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(yourNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(describeLabek, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(appointmentReasonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(studentIDTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                            .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstNameTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(studentIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(phoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                        .addComponent(phoneTextField)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(219, 219, 219)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(analyticsRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cyberRadio)
                                        .addComponent(mraRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(describeTextField))
                            .addComponent(uploadIdLabel)
                            .addComponent(mpmRadioButton)
                            .addComponent(pickDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(sendButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(uploadImageButton)
                        .addGap(37, 37, 37)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(appointForChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yourNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(studentIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(phoneLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(appointmentReasonLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointForChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(fieldofStudyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(misRadioButton)
                    .addComponent(analyticsRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mpmRadioButton)
                    .addComponent(mraRadioButton))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mbtRadio)
                    .addComponent(cyberRadio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pickDateLabel)
                .addGap(8, 8, 8)
                .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(describeLabek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(describeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(uploadIdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadImageButton)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sendButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void phoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneTextFieldActionPerformed

    private void misRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_misRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_misRadioButtonActionPerformed

    private void analyticsRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyticsRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_analyticsRadioActionPerformed

    private void describeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_describeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_describeTextFieldActionPerformed

    private void uploadImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImageButtonActionPerformed
        JFileChooser browseImageFile = new JFileChooser("C:\\Users\\Admin\\Pictures\\Screenshots");
        //Filter image extensions C:\Users\Admin\Pictures\Screenshots
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
 
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            selectedImagePath = selectedImageFile.getAbsolutePath();
            
            //Display image on jlable
            ImageIcon ii = new ImageIcon(selectedImagePath);
//            Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(imageLabel.getWidth(),imageLabel.getHeight(), Image.SCALE_SMOOTH);
 
            imageLabel.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_uploadImageButtonActionPerformed
private boolean validateFields() {
    // Validation for first name
    if (firstNameTextField.getText().isEmpty() || firstNameTextField.getText().length() > 15) {
        JOptionPane.showMessageDialog(null, "First name should not be empty");
        return false;
    }

    // Validation for last name
    if (lastNameTextField.getText().isEmpty() || lastNameTextField.getText().length() > 15) {
        JOptionPane.showMessageDialog(null, "Last name should not be empty");
        return false;
    }

    // Validation for student ID
    if (!studentIDTextField.getText().matches("\\d+")) {
        JOptionPane.showMessageDialog(null, "Student ID should contain only numbers.");
        return false;
    }

    // Validation for email
    if (!emailTextField.getText().matches("\\b[\\w.%-]+@[-.\\w]+\\.[A-Za-z]{2,4}\\b")) {
        JOptionPane.showMessageDialog(null, "Email should be in the format 'abc@gmail.com'.");
        return false;
    }

    // Validation for phone number
    if (!phoneTextField.getText().matches("\\d{10}")) {
        JOptionPane.showMessageDialog(null, "Phone number should contain 10 digits.");
        return false;
    }

    // Validation for appointment reason chooser
    if (appointForChooser.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(null, "Please select an appointment reason.");
        return false;
    }

    // Validation for field of study button group
    if (fieldOfStudyButtonGroup.getSelection() == null) {
        JOptionPane.showMessageDialog(null, "Please select a field of study.");
        return false;
    }

    // Validation for date picker (10 days from today)
    Date currentDate = new Date();
    long currentTime = currentDate.getTime();
    long selectedTime = datePicker.getDate().getTime();
    long tenDaysInMillis = 10 * 24 * 60 * 60 * 1000; // 10 days in milliseconds
    if (selectedTime - currentTime < tenDaysInMillis) {
        JOptionPane.showMessageDialog(null, "Please select a date at least 10 days from today.");
        return false;
    }

    // Validation for describe text field
    if (describeTextField.getText().length() < 100) {
        JOptionPane.showMessageDialog(null, "Please describe the reason in at least 100 characters.");
        return false;
    }

    return true; // All validations passed
}
    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        if (validateFields()){
            student newStudent = new student();
            try{
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                newStudent.setfName(firstNameTextField.getText());
                newStudent.setlName(lastNameTextField.getText());
                newStudent.setStuId(studentIDTextField.getText());
                newStudent.setEmail(emailTextField.getText());
                newStudent.setPhone(phoneTextField.getText());
                newStudent.setAppointmentReason(appointForChooser.getSelectedItem().toString());
                newStudent.setFieldOfStudy(fieldOfStudyButtonGroup.getSelection().getActionCommand());
                Date selectedDate = datePicker.getDate();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                // Format the selected date to a string
                String formattedDate = dateFormat.format(selectedDate);
                try {
                // Parse the formatted date string back to a Date object
                Date parsedDate = dateFormat.parse(formattedDate);
                // Set the parsed Date object to newStudent
                newStudent.setDate(parsedDate);
                } catch (ParseException ex) {
                ex.printStackTrace(); // Handle parsing exception here
                }
                String message = "Appointment confirmed";
            JOptionPane.showMessageDialog(this, message, "Appointment Confirmation", JOptionPane.INFORMATION_MESSAGE);
                //insert into db
                DatabaseConnector.addStudent(newStudent);

            } catch (Exception e){
            
            }
    }//GEN-LAST:event_sendButtonActionPerformed
    }
    String selectedImagePath;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton analyticsRadio;
    private javax.swing.JComboBox<String> appointForChooser;
    private javax.swing.JLabel appointmentReasonLabel;
    private javax.swing.JRadioButton cyberRadio;
    private com.toedter.calendar.JDateChooser datePicker;
    private javax.swing.JLabel describeLabek;
    private javax.swing.JTextField describeTextField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.ButtonGroup fieldOfStudyButtonGroup;
    private javax.swing.JLabel fieldofStudyLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JRadioButton mbtRadio;
    private javax.swing.JRadioButton misRadioButton;
    private javax.swing.JRadioButton mpmRadioButton;
    private javax.swing.JRadioButton mraRadioButton;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JLabel pickDateLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField studentIDTextField;
    private javax.swing.JLabel studentIdLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel uploadIdLabel;
    private javax.swing.JButton uploadImageButton;
    private javax.swing.JLabel yourNameLabel;
    // End of variables declaration//GEN-END:variables
}
